### ISSUE TITLE
Instructions very much unclear!

### ISSUE THREAD

**Issue by Gamey404** [gdzx/audiosource#11]
I don't know what exactly is missing in those instructions but I can't run ./audiosource if I never installed any related package on my computer! Am I supposed to build the code or something because from the releases it looks a lot like this will only output a apk file which I don't need because I installed the app over F-Droid and instructions don't mention it ether!

**Comment by gdzx** [comment]
Hi,

The [`audiosource`](https://github.com/gdzx/audiosource/blob/2b8f2fd1a3348b3e6fa627e6425468927ce264ad/audiosource) script is in the root of the repository.

Best regards,
