### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [gdzx/audiosource#12]
Could you please publish your app on F-Droid? :)

**Comment by gdzx** [comment]
Hi,

Unfortunately, I already have limited time to maintain this app, and managing a package for F-Droid would add quite a bit of extra efforts. I hope you understand!

However, if you really want to install it from F-Droid, there is a third-party repository that provides it: https://apt.izzysoft.de/fdroid/index/apk/fr.dzx.audiosource

Best regards,

**Comment by linsui** [comment]
> managing a package for F-Droid would add quite a bit of extra efforts

Generally it require little effort for such a simple pure java app. :) If you don't have time I can help you package it.

**Comment by gdzx** [comment]
Thank you for your offer. If you'd like to take the initiative, I have no objections to its inclusion in F-Droid. Feel free to make a PR for any necessary changes.

**Comment by linsui** [comment]
I opened a PR. https://github.com/gdzx/audiosource/pull/14 I'm not sure if it's finally reproducible. Could you please build an apk from it so that I can compare the apk?

**Comment by gdzx** [comment]
> I opened a PR. #14 I'm not sure if it's finally reproducible. Could you please build an apk from it so that I can compare the apk?

Here's my build: [audiosource.zip](https://github.com/user-attachments/files/16950480/audiosource.zip) (renamed as `.zip` since Github doesn't like `.apk`.)

**Comment by linsui** [comment]
Great, it's reproducible! Then #14 is ready to merge. :)

**Comment by linsui** [comment]
Can you release a new version? :)

**Comment by gdzx** [comment]
Done: [Audio Source v1.2](https://github.com/gdzx/audiosource/releases/tag/v1.2).

**Comment by linsui** [comment]
Thanks! It will be published in a week.

**Comment by licaon-kter** [comment]
@gdzx can you rename https://github.com/gdzx/audiosource/tree/master/fastlane/metadata/android/en-US/images/sevenInchScreenshots to `phoneScreenshots` maybe?

**Comment by gdzx** [comment]
@licaon-kter Done in https://github.com/gdzx/audiosource/commit/bdccc488edd582c75eec01b590ac248b4a19c17f.
