### ISSUE TITLE
Need clarification on instructions

### ISSUE THREAD

**Issue by rexendevar** [gdzx/audiosource#6]
The instructions say to run `./audiosource run` to launch the app, but I have no idea what this means. Is this via ADB on my computer, on my phone via Termux, or something else? I tried running it from termux and it said I didn't have permissions even though i just granted them to termux. I tried running it from my drawer and it popped up a permissions window before instantly exiting

**Comment by rexendevar** [comment]
the exact command i ran on Termux was `/storage/emulated/0/Sync/audiosource.apk run`

**Comment by gdzx** [comment]
Hi,

There is a script in the repository called `audiosource`. You must run it on your computer connected to the phone on which you installed the Audio Source APK. No need for Termux.

Best regards
