### ISSUE TITLE
Pipewire compatibility?

### ISSUE THREAD

**Issue by sudo-userv2** [gdzx/audiosource#7]
Is there a way to run it under pipewire ?

**Comment by gdzx** [comment]
Hi!

If you have `pipewire-pulse` then yes. Since it implements the same API as PulseAudio, the client tools from `libpulse` (like `pactl`) should just work.

Best regards

**Comment by alekksander** [comment]
Thanks! This should be mentioned in the app description. Pulse Audio is loosing popularity.
